### ISSUE TITLE
Contribute documentation 

### ISSUE THREAD

**Issue by ricardo-maestas** [united-manufacturing-hub/umh.docs.umh.app#152]
### Describe the issue

When I was setting up my local environment to make documentation contributions, I found conflicting information across these pages:

[readme.md](https://github.com/united-manufacturing-hub/umh.docs.umh.app/blob/b5e37f13019813820214e5de65a81bab76dc36c4/README.md)
[setup-environment.md](https://umh.docs.umh.app/docs/development/contribute/documentation/setup-environment/)
[add-documentation.md](https://umh.docs.umh.app/docs/development/contribute/new-content/add-documentation/)

### What did you expect to happen?

There should be accurate instructions for new contributors to setup their local environments and add documentation.

### Solution

I recommend the following:

1. [readme.md](http://readme.md/) contains redundant information in the **Prerequisites** and **Running the website locally using Hugo** sections. These sections should be removed. A user who finds this document while browsing the GitHub repo should be directed to the linked pages in the **Contributing to the docs** section.
2. Make the following corrections to the setup-environment page.
    1. List Git lfs as a prerequisite
    2. Include GNU make and GNU awk as Required pre-requisites.
    3. In the Clone the repository section, change the following
        
        ```bash
        git remote add origin https://github.com/united-manufacturing-hub/umh.docs.umh.app.git
        # or: git remote add upstream git@github.com:united-manufacturing-hub/umh.docs.umh.app.git
        
        # Never push to upstream master
        git remote set-url --push origin no_push
        ```
        
        to
        
        ```bash
        git remote add upstream https://github.com/united-manufacturing-hub/umh.docs.umh.app.git
        
        # Never push to upstream master
        git remote set-url --push upstream no_push
        ```
        
    4. In the Install dependencies section, add instructions to first “browse to the directory that contains the repository” before running `make module-init`.
    5. In the Run the development server section
        
        See https://discord.com/channels/700613971941785680/1149827758621462569 (a separate issue may be opened to address this)

3. Make the following corrections to the add-documentation page.
    1. In the Create a local clone and set the upstream section
        1. Remove step 2, as this was presumably addressed in [Setup Local Environment](https://umh.docs.umh.app/docs/development/contribute/documentation/setup-environment/)
        2. Output of `git remote -v` in step 3 should be the following
            
            ```bash
            origin  https://github.com/ricardo-maestas/umh.docs.umh.app.git (fetch)
            origin  https://github.com/ricardo-maestas/umh.docs.umh.app.git (push)
            upstream        https://github.com/united-manufacturing-hub/umh.docs.umh.app.git (fetch)
            upstream        no_push (push)
            ```
            
    2. In the Preview your changes locally section
        1. Provide instructions to run `make serve` instead of `hugo server --buildFuture`
    3. In the Create a branch section, add notes about naming branches
        1. Syntax
            [purpose]/[id]/[title] where
            purpose is docs, feat, or fix and
            id is the issue identifier, or xxx if there is none

**Comment by DaruZero** [comment]
Hello @ricardo-maestas and thank you for bringing up these issues. I agree with most of what you said, but I would nonetheless like to go through your points.
1. Yes, having duplicated instruction is not ideal and harder to maintain. We should rewrite the README to be more in line with other OSS documentation repositories, like [GitHub](https://github.com/github/docs) or [Docker](https://github.com/docker/docs)
2. setup-environment:
  1. Git LFS should be added to the requirements
  2. GMake and Gawk are not required though, as one can choose to run the commands. We want to make it as easy as possible to contribute, and installing lots of software is not the best, especially for non-developers or people that just started to dip their toes in the development world. So listing them as recommended but not required is the nicest approach, and we should just add the two options (using `make` or the full command`) in other parts of the documentation
  3. Yes, it should be specified to navigate into the repo's directory
  4. As I said on the Discord thread, I am running a Windows 11 environment, and `make module-check` works as intended. We should investigate more why it doesn't on your machine, and maybe address the recommended software versions / environment in the documentation
3. add-documentation:
  1. Yes, we can remove the steps to fork the repo and create a local clone, but it should also be more clear that those steps are in the setup page
  2. Like I said before, we should give the user the option to use both the `make` command or the full command
  3. I agree that the Create a branch section is not very clear, and could be improved.

Since these are not big changes, you can start working on them if you like. Otherwise I could take over. Let me know what you prefer

**Comment by ricardo-maestas** [comment]
Thanks @DaruZero . I will go ahead and work on these.
